### ISSUE TITLE
Messages to Telegram not sent

### ISSUE THREAD

**Issue by ovidiub13** [FruitieX/teleirc#10]
When a message is sent on IRC and the bot is mentioned, the message is printed bu console.log() but 2 seconds after that this error shows up and the message never arrives in Telegram:

    Possibly unhandled StatusCodeError: 400 - {"ok":false,"error_code":400,"description":"Error: PEER_ID_INVALID"}
        at new StatusCodeError (/home/aaron/teleirc/node_modules/telegram-bot/node_modules/request-promise/lib/errors.js:26:15)
        at Request.RP$callback [as _callback] (/home/aaron/teleirc/node_modules/telegram-bot/node_modules/request-promise/lib/rp.js:64:32)
        at Request.self.callback (/home/aaron/teleirc/node_modules/telegram-bot/node_modules/request-promise/node_modules/request/request.js:198:22)
        at Request.EventEmitter.emit (events.js:98:17)
        at Request.<anonymous> (/home/aaron/teleirc/node_modules/telegram-bot/node_modules/request-promise/node_modules/request/request.js:1073:14)
        at Request.EventEmitter.emit (events.js:117:20)
        at IncomingMessage.<anonymous> (/home/aaron/teleirc/node_modules/telegram-bot/node_modules/request-promise/node_modules/request/request.js:1019:12)
        at IncomingMessage.EventEmitter.emit (events.js:117:20)
        at _stream_readable.js:920:16
        at process._tickCallback (node.js:415:13)

**Comment by FruitieX** [comment]
Did you enter your bot API token correctly into `~/.teleirc_config.js`?

**Comment by ahoneybun** [comment]
I'm not sure what it was but now it works, most likely a config issue I made thanks @FruitieX !
