### ISSUE TITLE
irc -> telegram messages lost due to timeout error

### ISSUE THREAD

**Issue by fauno** [FruitieX/teleirc#160]
```
verbose: >> relaying to TG: <fauno_> tira un timeout
Unhandled rejection TimeoutError: operation timed out
    at afterTimeout (/home/fauno/.nvm/versions/node/v4.2.6/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/timers.js:16:15)
    at timeoutTimeout (/home/fauno/.nvm/versions/node/v4.2.6/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/timers.js:59:9)
    at Timer.listOnTimeout (timers.js:92:15)
Unhandled rejection Error: connect ETIMEDOUT 149.154.167.200:443
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
Unhandled rejection Error: connect ETIMEDOUT 149.154.167.200:443
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
Unhandled rejection TimeoutError: operation timed out
    at afterTimeout (/home/fauno/.nvm/versions/node/v4.2.6/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/timers.js:16:15)
    at timeoutTimeout (/home/fauno/.nvm/versions/node/v4.2.6/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/timers.js:59:9)
    at Timer.listOnTimeout (timers.js:92:15)
Unhandled rejection TimeoutError: operation timed out
    at afterTimeout (/home/fauno/.nvm/versions/node/v4.2.6/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/timers.js:16:15)
    at timeoutTimeout (/home/fauno/.nvm/versions/node/v4.2.6/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/timers.js:59:9)
    at Timer.listOnTimeout (timers.js:92:15)
Unhandled rejection TimeoutError: operation timed out
    at afterTimeout (/home/fauno/.nvm/versions/node/v4.2.6/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/timers.js:16:15)
    at timeoutTimeout (/home/fauno/.nvm/versions/node/v4.2.6/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/timers.js:59:9)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by Mikaela** [comment]
Is this still happening? I think Telegram bot API might have been down at the time this issue was opened.
