### ISSUE TITLE
Current develop is broken

### ISSUE THREAD

**Issue by Mikaela** [FruitieX/teleirc#196]
```
info: using config file from: /home/users/mikaela/.teleirc/config.js
info: forcing log level to "silly"
node-telegram-bot-api deprecated Node.js v5.x and below will no longer be supported in the future module.js:409:26
error: channel * not found in config!
error: channel * not found in config!
error: channel * not found in config!
error: channel * not found in config!
error: channel * not found in config!
error: channel * not found in config!
error: channel * not found in config!
error: channel * not found in config!
/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/src/client.js:295
    this.connection.write(this.rawString.apply(this, arguments));
                   ^

TypeError: Cannot read property 'write' of undefined
    at IrcClient.raw (/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/src/client.js:295:20)
    at /home/users/mikaela/src/github/fruitiex/teleirc/src/irc/index.js:48:25
    at Array.forEach (native)
    at IrcClient.<anonymous> (/home/users/mikaela/src/github/fruitiex/teleirc/src/irc/index.js:47:31)
    at IrcClient.emit (/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/node_modules/eventemitter3/index.js:129:35)
    at /home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/src/client.js:185:20
    at next (/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/node_modules/middleware-handler/index.js:42:18)
    at MiddlewareHandler.handle (/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/node_modules/middleware-handler/index.js:64:3)
    at IrcCommandHandler.<anonymous> (/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/src/client.js:179:34)
    at IrcCommandHandler.emit (/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/node_modules/eventemitter3/index.js:130:35)
    at IrcCommandHandler.emit (/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/src/commands/handler.js:95:23)
    at IrcCommandHandler.handlers.RPL_WELCOME (/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/src/commands/handlers/registration.js:11:14)
    at IrcCommandHandler.executeCommand (/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/src/commands/handler.js:62:37)
    at IrcCommandHandler.dispatch (/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/src/commands/handler.js:49:14)
    at /home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/src/client.js:103:36
    at next (/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/node_modules/middleware-handler/index.js:42:18)
    at MiddlewareHandler.handle (/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/node_modules/middleware-handler/index.js:64:3)
    at Connection.<anonymous> (/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/src/client.js:97:31)
    at Connection.emit (/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/node_modules/eventemitter3/index.js:130:35)
    at Connection.processReadBuffer (/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/src/connection.js:273:14)
    at Connection.socketLine (/home/users/mikaela/src/github/fruitiex/teleirc/node_modules/irc-framework/src/connection.js:101:14)
    at emitOne (events.js:77:13)
```

* Debian GNU/Linux 8.9 (jessie)
* node v4.8.4

**Comment by Mikaela** [comment]
I am currently using c550853 which is the last working version that I have ran.

**Comment by adedomin** [comment]
it might be a this problem: 
line 48 of src/irc/index.js: nodeIrc.raw.apply(null, cmd.split(' '));

though I'm running this fine on node v6. not sure what has changed. maybe something about how non-strict mode works and null thisArgs?

**Comment by Mikaela** [comment]
https://github.com/FruitieX/teleirc/commit/f1c8c4af49988dfb5e0d701b138b42899cf1b756
