### ISSUE TITLE
tgChatId of undefined error

### ISSUE THREAD

**Issue by ImTheDeveloper** [FruitieX/teleirc#197]
Any idea what might be causing this issue?

I've removed all of the chat files from the .teleirc folder and restarted to try and ensure there isn't some bad chat config but it still seems to happen once a day at least.

```
error: No chat_id set! Add me to a Telegram group and say hi so I can find your group's chat_id!
info: storing chat ID: -242469221
info: successfully stored chat ID in /home/xxx/.teleirc/210.chatid
info: storing chat ID: -1001133984872
info: successfully stored chat ID in /home/xxx/.teleirc/#status.chatid
warn: unsupported entity type: url
{ message_id: 3654,
  from: { id: 47603818, first_name: 'xxx', username: 'xxx' },
  chat: { id: -1001133672368, title: '#xxx', type: 'supergroup' },
  date: 1502653506,
  text: 'http://xxx.xxx.com/showthread.php?p=3259685',
  entities: [ { type: 'url', offset: 0, length: 54 } ] }
/usr/local/lib/node_modules/teleirc/node_modules/irc/lib/irc.js:849
                        throw err;
                        ^

TypeError: Cannot read property 'tgChatId' of undefined
    at Object.send (/usr/local/lib/node_modules/teleirc/src/tg/index.js:35:33)
    at msgCallback (/usr/local/lib/node_modules/teleirc/src/index.js:26:20)
    at Client.<anonymous> (/usr/local/lib/node_modules/teleirc/src/irc/index.js:98:17)
    at emitMany (events.js:127:13)
    at Client.emit (events.js:204:7)
    at Client.<anonymous> (/usr/local/lib/node_modules/teleirc/node_modules/irc/lib/irc.js:595:22)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:191:7)
    at iterator (/usr/local/lib/node_modules/teleirc/node_modules/irc/lib/irc.js:846:26)
    at Array.forEach (native)
    at Socket.handleData (/usr/local/lib/node_modules/teleirc/node_modules/irc/lib/irc.js:841:15)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:554:20)
```

Also noticed for 1 of my chats the /names command does not work. It might be related? The relay however does work ok in all rooms.

**Comment by ImTheDeveloper** [comment]
I've set teleirc to run via pm2 and noticed that it seems to be restarting every 2 hours:


pa, [14.08.17 11:03]
TG has joined

pa, [14.08.17 13:17]
TG has joined

pa, [14.08.17 15:18]
TG has joined

Coincidence?

**Comment by ImTheDeveloper** [comment]
This was due to some dodgy config file I think.
I reset the file and it was fine.
