### ISSUE TITLE
Error on setting +o to bot

### ISSUE THREAD

**Issue by ImTheDeveloper** [FruitieX/teleirc#199]
Seems to happen when setting the bot to operator +O in chan

```
6|teleirc  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
6|teleirc  | TimeoutError: operation timed out
6|teleirc  |     at afterTimeout (/usr/local/lib/node_modules/teleirc/node_modules/bluebird/js/main/timers.js:16:15)
6|teleirc  |     at Timeout.timeoutTimeout [as _onTimeout] (/usr/local/lib/node_modules/teleirc/node_modules/bluebird/js/main/timers.js:59:9)
6|teleirc  |     at ontimeout (timers.js:365:14)
6|teleirc  |     at tryOnTimeout (timers.js:237:5)
6|teleirc  |     at Timer.listOnTimeout (timers.js:207:5)
6|teleirc  | Unhandled rejection TimeoutError: operation timed out
6|teleirc  |     at afterTimeout (/usr/local/lib/node_modules/teleirc/node_modules/bluebird/js/main/timers.js:16:15)
6|teleirc  |     at Timeout.timeoutTimeout [as _onTimeout] (/usr/local/lib/node_modules/teleirc/node_modules/bluebird/js/main/timers.js:59:9)
6|teleirc  |     at ontimeout (timers.js:365:14)
6|teleirc  |     at tryOnTimeout (timers.js:237:5)
6|teleirc  |     at Timer.listOnTimeout (timers.js:207:5)
6|teleirc  | Unhandled rejection TimeoutError: operation timed out
6|teleirc  |     at afterTimeout (/usr/local/lib/node_modules/teleirc/node_modules/bluebird/js/main/timers.js:16:15)
6|teleirc  |     at Timeout.timeoutTimeout [as _onTimeout] (/usr/local/lib/node_modules/teleirc/node_modules/bluebird/js/main/timers.js:59:9)
6|teleirc  |     at ontimeout (timers.js:365:14)
6|teleirc  |     at tryOnTimeout (timers.js:237:5)
6|teleirc  |     at Timer.listOnTimeout (timers.js:207:5)
6|teleirc  | Unhandled rejection TimeoutError: operation timed out
6|teleirc  |     at afterTimeout (/usr/local/lib/node_modules/teleirc/node_modules/bluebird/js/main/timers.js:16:15)
6|teleirc  |     at Timeout.timeoutTimeout [as _onTimeout] (/usr/local/lib/node_modules/teleirc/node_modules/bluebird/js/main/timers.js:59:9)
6|teleirc  |     at ontimeout (timers.js:365:14)
6|teleirc  |     at tryOnTimeout (timers.js:237:5)
6|teleirc  |     at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by adedomin** [comment]
is this the latest development branch? or another branch? because I need to know what irc dependency this issue crops up in. i can't reproduce myself.

**Comment by ImTheDeveloper** [comment]
This was a problem with the underling node-irc library and I managed to put a fix in to that. However the library itself is still riddled with problems. I believe you are looking to move to another lib?
