### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined when unbanning on IRC

### ISSUE THREAD

**Issue by 14mRh4X0r** [FruitieX/teleirc#218]
When unbanning someone on IRC, the bridge crashes with the following message (full path redacted):

```
/home/telegram_irc_bridge/teleirc/node_modules/irc/lib/irc.js:849
                        throw err;
                        ^

TypeError: Cannot read property 'filter' of undefined
    at chanModes ([...]/node_modules/irc/lib/irc.js:300:37)
    at [...]/node_modules/irc/lib/irc.js:319:25
    at Array.forEach (native)
    at Client.<anonymous> ([...]/node_modules/irc/lib/irc.js:270:26)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at iterator ([...]/node_modules/irc/lib/irc.js:846:26)
    at Array.forEach (native)
    at Socket.handleData ([...]/node_modules/irc/lib/irc.js:841:15)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:540:20)
```

**Comment by Mikaela** [comment]
I cannot reproduce this, could you give some example command for unbanning? And possibly your /version?

* Version: teleirc git-226c7f8 (on branch: develop), npm-0.4.7

**Comment by adedomin** [comment]
this is a bug with node-irc lib used in older versions. this should be closed.

**Comment by 14mRh4X0r** [comment]
Ah, sorry about that, I hadn't checked for newer versions. Glad to hear it's resolved :)
