### ISSUE TITLE
TypeError: Cannot read property 'tgChatId' of undefined 

### ISSUE THREAD

**Issue by FerdinandoLM** [FruitieX/teleirc#225]
I can't solve an error i got on teleirc

```
verbose: << relaying to IRC: test 
/usr/lib/node_modules/teleirc/src/tg/index.js:50
            if (!message.channel.tgChatId) {
                                 ^

TypeError: Cannot read property 'tgChatId' of undefined
    at Object.send (/usr/lib/node_modules/teleirc/src/tg/index.js:50:34)
    at msgCallback (/usr/lib/node_modules/teleirc/src/index.js:38:20)
    at IrcClient.<anonymous> (/usr/lib/node_modules/teleirc/src/irc/index.js:262:9)
    at IrcClient.emit (/usr/lib/node_modules/teleirc/node_modules/eventemitter3/index.js:129:35)
    at /usr/lib/node_modules/teleirc/node_modules/irc-framework/src/client.js:185:20
    at next (/usr/lib/node_modules/teleirc/node_modules/middleware-handler/index.js:42:18)
    at MiddlewareHandler.handle (/usr/lib/node_modules/teleirc/node_modules/middleware-handler/index.js:64:3)
    at IrcCommandHandler.<anonymous> (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/client.js:179:34)
    at IrcCommandHandler.emit (/usr/lib/node_modules/teleirc/node_modules/eventemitter3/index.js:130:35)
    at IrcCommandHandler.emit (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/commands/handler.js:95:23)
    at IrcCommandHandler.RPL_ENDOFWHO (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/commands/handlers/misc.js:100:14)
    at IrcCommandHandler.executeCommand (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/commands/handler.js:62:37)
    at IrcCommandHandler.dispatch (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/commands/handler.js:49:14)
    at /usr/lib/node_modules/teleirc/node_modules/irc-framework/src/client.js:103:36
    at next (/usr/lib/node_modules/teleirc/node_modules/middleware-handler/index.js:42:18)
    at MiddlewareHandler.handle (/usr/lib/node_modules/teleirc/node_modules/middleware-handler/index.js:64:3)
    at Connection.<anonymous> (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/client.js:97:31)
    at Connection.emit (/usr/lib/node_modules/teleirc/node_modules/eventemitter3/index.js:130:35)
    at Connection.processReadBuffer (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/connection.js:273:14)
    at Connection.socketLine (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/connection.js:101:14)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)

```

I saw on issue #197 an almost identical error, but resetting the config file doesn't seem to work for me.

**Comment by Mikaela** [comment]
Which version of TeleIRC are you using? And node?

**Comment by l1ge** [comment]
teleirc v0.4.8
node v11.6.0

I have similar error but only when I connect to my ZNC server. It works for a few minute, i can see messages between telegram and IRC and then it crashes with this error :

```
 /usr/lib/node_modules/teleirc/src/tg/index.js:50
            if (!message.channel.tgChatId) {
                                 ^

TypeError: Cannot read property 'tgChatId' of undefined
    at Object.send (/usr/lib/node_modules/teleirc/src/tg/index.js:50:34)
    at msgCallback (/usr/lib/node_modules/teleirc/src/index.js:38:20)
    at IrcClient.<anonymous> (/usr/lib/node_modules/teleirc/src/irc/index.js:262:9)
    at IrcClient.emit (/usr/lib/node_modules/teleirc/node_modules/eventemitter3/index.js:129:35)
    at /usr/lib/node_modules/teleirc/node_modules/irc-framework/src/client.js:197:24
    at next (/usr/lib/node_modules/teleirc/node_modules/middleware-handler/index.js:42:18)
    at MiddlewareHandler.handle (/usr/lib/node_modules/teleirc/node_modules/middleware-handler/index.js:64:3)
    at IrcCommandHandler.<anonymous> (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/client.js:191:38)
    at IrcCommandHandler.emit (/usr/lib/node_modules/teleirc/node_modules/eventemitter3/index.js:130:35)
    at IrcCommandHandler.emit (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/commands/handler.js:92:27)
    at IrcCommandHandler.RPL_ENDOFWHO (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/commands/handlers/misc.js:102:14)
    at IrcCommandHandler.executeCommand (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/commands/handler.js:59:41)
    at IrcCommandHandler.dispatch (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/commands/handler.js:46:18)
    at /usr/lib/node_modules/teleirc/node_modules/irc-framework/src/client.js:108:40
    at next (/usr/lib/node_modules/teleirc/node_modules/middleware-handler/index.js:42:18)
    at MiddlewareHandler.handle (/usr/lib/node_modules/teleirc/node_modules/middleware-handler/index.js:64:3)
    at Connection.<anonymous> (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/client.js:102:35)
    at Connection.emit (/usr/lib/node_modules/teleirc/node_modules/eventemitter3/index.js:130:35)
    at Connection.processReadBuffer (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/connection.js:278:18)
    at Connection.socketLine (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/connection.js:100:18)
    at Connection.emit (events.js:188:13)
    at lines.forEach._line (/usr/lib/node_modules/teleirc/node_modules/irc-framework/src/transports/net.js:169:12)
```


When i don't connect via ZNC but directly to the IRC server it works fine.

**Comment by l1ge** [comment]
Actually it works when I use teleric without -vvv parameter
