### ISSUE TITLE
Build fails at node-icu-charset-detector

### ISSUE THREAD

**Issue by DavidCWGA** [FruitieX/teleirc#38]
```
node-icu-charset-detector.target.mk:88: recipe for target 'Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o' failed
make: *** [Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o] Error 1
make: Leaving directory '/usr/lib/node_modules/teleirc/node_modules/node-icu-charset-detector/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.5-x86_64-linode61
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/teleirc/node_modules/node-icu-charset-detector
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
```

Attempting to build on Debian Jessie with node installed from the node repository.

**Comment by DavidCWGA** [comment]
Building from git works fine, however.

**Comment by FruitieX** [comment]
That's weird, it builds here... I'll have to test on Debian, thanks for reporting.

**Comment by martinie** [comment]
You'll sort it with: apt-get install libicu-dev

**Comment by DavidCWGA** [comment]
> apt-get install libicu-dev

Actually I'd already done that. Before I did, I got a different error about a missing file. (Which I didn't save. Sorry.)

**Comment by martinie** [comment]
From what I remember I had to do a npm install -g node-gyp-install (it was 5am, I was half asleep) before I used apt-get install libicu-dev

**Comment by FruitieX** [comment]
I think this is fixed now in latest master, as the node-irc module has been updated. IIRC they are using a newer version of node-icu-charset-detector which hopefully works around this problem.
