### ISSUE TITLE
Got jammed sometimes

### ISSUE THREAD

**Issue by Bysmyyr** [FruitieX/teleirc#9]
This happens 1-5 times per week. Needs manual restart.

Possibly unhandled StatusCodeError: 504 - <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.9.1</center>
</body>
</html>

    at new StatusCodeError (/home/bysmyyr/teleirc/node_modules/telegram-bot/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback] (/home/bysmyyr/teleirc/node_modules/telegram-bot/node_modules/request-promise/lib/rp.js:64:32)
    at Request.self.callback (/home/bysmyyr/teleirc/node_modules/telegram-bot/node_modules/request-promise/node_modules/request/request.js:198:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/bysmyyr/teleirc/node_modules/telegram-bot/node_modules/request-promise/node_modules/request/request.js:1073:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/bysmyyr/teleirc/node_modules/telegram-bot/node_modules/request-promise/node_modules/request/request.js:1019:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
Possibly unhandled StatusCodeError: 504 - <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.9.1</center>
</body>
</html>

    at new StatusCodeError (/home/bysmyyr/teleirc/node_modules/telegram-bot/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback] (/home/bysmyyr/teleirc/node_modules/telegram-bot/node_modules/request-promise/lib/rp.js:64:32)
    at Request.self.callback (/home/bysmyyr/teleirc/node_modules/telegram-bot/node_modules/request-promise/node_modules/request/request.js:198:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/bysmyyr/teleirc/node_modules/telegram-bot/node_modules/request-promise/node_modules/request/request.js:1073:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/bysmyyr/teleirc/node_modules/telegram-bot/node_modules/request-promise/node_modules/request/request.js:1019:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by FruitieX** [comment]
I have noticed this with other telegram bots as well, but it's gotten better recently. Usually you don't even need a restart, it just takes a long time for the bot to reconnect. I suspect it was some problem with Telegram's servers, as I haven't seen this happen in about a week now.

It could make sense to eventually switch to another telegram bot API module which is more up to date, but for now I'll close the issue. Please re-open if the problem still persists.
