### ISSUE TITLE
/names@bot is currently broken

### ISSUE THREAD

**Issue by Mikaela** [FruitieX/teleirc#95]
The bot just doesn't reply anything.

**Comment by Mikaela** [comment]
I think this is broken again.

```
tree 90adb354879fa335d67b4fdea76f3ccb2ef90ddd
parent 35f75063650d9a6fbe1f15f0ee7ee46333996cb8
author zertrin <> 1461498565 +0200
committer Rasmus Eskola <> 1461498565 +0300

Update Dockerfile and the README for Docker install (#100)%     
```

**Comment by Mikaela** [comment]
This has mysteriously started working without me doing anything.

**Comment by FruitieX** [comment]
I had a similar issue which resolved itself by re-adding the bot... Possibly some problem on telegram's side. Will keep the issue open as this needs more investigation.

**Comment by Mikaela** [comment]
Morning testing:

* My personal group (for one RSS feed spam bot mainly) *doesn't work*
* Antergos group *works*
* Antergos ops group *works*

**Comment by FruitieX** [comment]
Works for me as well :-)

Does it not even work after removing and re-adding the bot, after having told BotFather also about the `/names` command?

**Comment by Mikaela** [comment]
```
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: debug: got tg msg:
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: { message_id: 3461,
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: from:
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: { id: 164534060,
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: first_name: 'Mikaela',
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: last_name: 'Suomalainen 🇫🇮',
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: username: 'Kissaela' },
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: chat:
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: { id: -1001046516179,
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: title: 'Mikaela.info',
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: username: 'MikaelaDotInfo',
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: type: 'supergroup' },
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: date: 1465372721,
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: text: '/names@Teleuforiabot',
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: entities: [ { type: 'bot_command', offset: 0, length: 20 } ] }
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: error: No nicklist received!
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: Unhandled rejection TypeError: Cannot read property 'sort' of undefined
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: at msgCallback (/usr/local/lib/node_modules/teleirc/src/index.js:42:26)
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: at /usr/local/lib/node_modules/teleirc/src/tg/index.js:26:21
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: at Object.exports.parseMsg (/usr/local/lib/node_modules/teleirc/src/tg/util.js:217:16)
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: at null.<anonymous> (/usr/local/lib/node_modules/teleirc/src/tg/index.js:23:20)
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: at emitOne (events.js:77:13)
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: at emit (events.js:169:7)
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: at TelegramBot._processUpdate (/usr/local/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/src/telegram.js:78:10)
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: at null.<anonymous> (/usr/local/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/src/telegramPolling.js:36:14)
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: at Array.forEach (native)
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: at null.<anonymous> (/usr/local/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/src/telegramPolling.js:33:15)
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: at tryCatcher (/usr/local/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/util.js:26:23)
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:507:31)
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: at Promise._settlePromiseAt (/usr/local/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:581:18)
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: at Promise._settlePromises (/usr/local/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:697:14)
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: at Async._drainQueue (/usr/local/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:123:16)
kesä 08 10:58:42 vardiera.mikaela.info teleirc[5522]: at Async._drainQueues (/usr/local/lib/node_modules/teleirc/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:133:10)
```

**Comment by Cadair** [comment]
I am also having this issue, I tried removing and re adding the not (after telling botfather about the commands, and still nothing.)

**Comment by Cadair** [comment]
/topic is also not working for me, the bot just responds with No topic for channel...
